name: danleephoto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3d9bd8'
    - '#000000'
    - '#5e5e5e'
    - '#c5c5c5'
  brandStrength: 0.75
  lightness: null
  saturation: 0
  rhythmicContrast: null
purpose: []
